### ISSUE TITLE
Error in workflow 'com.sverdlik.michael'

### ISSUE THREAD

**Issue by BrianGilbert** [m1keil/alfred-vagrant-workflow#17]
![monosnap 2016-06-01 07-54-42](https://cloud.githubusercontent.com/assets/114017/15691785/1dd23f5c-27ce-11e6-9909-7e1c31d0a41b.png)
After trying to up or down a box if I reveal alfred again I see the following error.

**Comment by m1keil** [comment]
Hey @BrianGilbert,
I'll publish v2.0 in the next couple of days, it should fix this and simplify the workflow.

In the meantime, any chance you can share the log as well? You can open it by doing 'vagrant workflow:openlog' 
Just copy over any log lines that appear there after you hit this error.
Thanks

**Comment by BrianGilbert** [comment]
Updated and getting errors, log below:

```
11:38:32 workflow.py:2154 DEBUG    Workflow version : 2.0.0
11:38:32 workflow.py:1556 DEBUG    Reading settings from `/Users/brian/Library/Application Support/Alfred 3/Workflow Data/com.sverdlik.michael/settings.json` ...
11:38:32 workflow.py:2176 ERROR    Unable to normalize state: aborted
Traceback (most recent call last):
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/workflow/workflow.py", line 2169, in run
    func(self)
  File "vagrantup.py", line 185, in main
    do_list(wf, args.list)
  File "vagrantup.py", line 117, in do_list
    add_machines(wf, _safe_get(args, 0))
  File "vagrantup.py", line 48, in add_machines
    vi = Index(fh)
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 133, in __init__
    self.machines = self.parse_v1_machines(content['machines'])
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 126, in parse_v1_machines
    return {key: Machine(key=key, **val) for key, val in mdict.iteritems()}
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 126, in <dictcomp>
    return {key: Machine(key=key, **val) for key, val in mdict.iteritems()}
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 26, in __init__
    self.normalized_state = self.normalize_state(self.state)
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 56, in normalize_state
    raise ValueError('Unable to normalize state: {0}'.format(state))
ValueError: Unable to normalize state: aborted
11:38:32 workflow.py:2179 INFO     For assistance, see: https://github.com/m1keil/alfred-vagrant-workflow
11:38:32 workflow.py:2197 DEBUG    Workflow finished in 0.022 seconds.
11:38:41 workflow.py:2154 DEBUG    Workflow version : 2.0.0
11:38:41 workflow.py:1556 DEBUG    Reading settings from `/Users/brian/Library/Application Support/Alfred 3/Workflow Data/com.sverdlik.michael/settings.json` ...
11:38:41 workflow.py:2176 ERROR    Unable to normalize state: aborted
Traceback (most recent call last):
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/workflow/workflow.py", line 2169, in run
    func(self)
  File "vagrantup.py", line 185, in main
    do_list(wf, args.list)
  File "vagrantup.py", line 117, in do_list
    add_machines(wf, _safe_get(args, 0))
  File "vagrantup.py", line 48, in add_machines
    vi = Index(fh)
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 133, in __init__
    self.machines = self.parse_v1_machines(content['machines'])
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 126, in parse_v1_machines
    return {key: Machine(key=key, **val) for key, val in mdict.iteritems()}
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 126, in <dictcomp>
    return {key: Machine(key=key, **val) for key, val in mdict.iteritems()}
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 26, in __init__
    self.normalized_state = self.normalize_state(self.state)
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 56, in normalize_state
    raise ValueError('Unable to normalize state: {0}'.format(state))
ValueError: Unable to normalize state: aborted
11:38:41 workflow.py:2179 INFO     For assistance, see: https://github.com/m1keil/alfred-vagrant-workflow
11:38:41 workflow.py:2197 DEBUG    Workflow finished in 0.018 seconds.
11:38:48 workflow.py:2154 DEBUG    Workflow version : 2.0.0
11:38:48 workflow.py:1556 DEBUG    Reading settings from `/Users/brian/Library/Application Support/Alfred 3/Workflow Data/com.sverdlik.michael/settings.json` ...
11:38:48 workflow.py:2176 ERROR    Unable to normalize state: aborted
Traceback (most recent call last):
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/workflow/workflow.py", line 2169, in run
    func(self)
  File "vagrantup.py", line 185, in main
    do_list(wf, args.list)
  File "vagrantup.py", line 117, in do_list
    add_machines(wf, _safe_get(args, 0))
  File "vagrantup.py", line 48, in add_machines
    vi = Index(fh)
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 133, in __init__
    self.machines = self.parse_v1_machines(content['machines'])
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 126, in parse_v1_machines
    return {key: Machine(key=key, **val) for key, val in mdict.iteritems()}
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 126, in <dictcomp>
    return {key: Machine(key=key, **val) for key, val in mdict.iteritems()}
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 26, in __init__
    self.normalized_state = self.normalize_state(self.state)
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 56, in normalize_state
    raise ValueError('Unable to normalize state: {0}'.format(state))
ValueError: Unable to normalize state: aborted
11:38:48 workflow.py:2179 INFO     For assistance, see: https://github.com/m1keil/alfred-vagrant-workflow
11:38:48 workflow.py:2197 DEBUG    Workflow finished in 0.017 seconds.
11:38:49 workflow.py:2154 DEBUG    Workflow version : 2.0.0
11:38:49 workflow.py:1556 DEBUG    Reading settings from `/Users/brian/Library/Application Support/Alfred 3/Workflow Data/com.sverdlik.michael/settings.json` ...
11:38:49 workflow.py:2176 ERROR    Unable to normalize state: aborted
Traceback (most recent call last):
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/workflow/workflow.py", line 2169, in run
    func(self)
  File "vagrantup.py", line 185, in main
    do_list(wf, args.list)
  File "vagrantup.py", line 117, in do_list
    add_machines(wf, _safe_get(args, 0))
  File "vagrantup.py", line 48, in add_machines
    vi = Index(fh)
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 133, in __init__
    self.machines = self.parse_v1_machines(content['machines'])
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 126, in parse_v1_machines
    return {key: Machine(key=key, **val) for key, val in mdict.iteritems()}
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 126, in <dictcomp>
    return {key: Machine(key=key, **val) for key, val in mdict.iteritems()}
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 26, in __init__
    self.normalized_state = self.normalize_state(self.state)
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 56, in normalize_state
    raise ValueError('Unable to normalize state: {0}'.format(state))
ValueError: Unable to normalize state: aborted
11:38:49 workflow.py:2179 INFO     For assistance, see: https://github.com/m1keil/alfred-vagrant-workflow
11:38:49 workflow.py:2197 DEBUG    Workflow finished in 0.016 seconds.
11:38:49 workflow.py:2154 DEBUG    Workflow version : 2.0.0
11:38:49 workflow.py:1556 DEBUG    Reading settings from `/Users/brian/Library/Application Support/Alfred 3/Workflow Data/com.sverdlik.michael/settings.json` ...
11:38:49 workflow.py:2176 ERROR    Unable to normalize state: aborted
Traceback (most recent call last):
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/workflow/workflow.py", line 2169, in run
    func(self)
  File "vagrantup.py", line 185, in main
    do_list(wf, args.list)
  File "vagrantup.py", line 117, in do_list
    add_machines(wf, _safe_get(args, 0))
  File "vagrantup.py", line 48, in add_machines
    vi = Index(fh)
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 133, in __init__
    self.machines = self.parse_v1_machines(content['machines'])
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 126, in parse_v1_machines
    return {key: Machine(key=key, **val) for key, val in mdict.iteritems()}
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 126, in <dictcomp>
    return {key: Machine(key=key, **val) for key, val in mdict.iteritems()}
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 26, in __init__
    self.normalized_state = self.normalize_state(self.state)
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 56, in normalize_state
    raise ValueError('Unable to normalize state: {0}'.format(state))
ValueError: Unable to normalize state: aborted
11:38:49 workflow.py:2179 INFO     For assistance, see: https://github.com/m1keil/alfred-vagrant-workflow
11:38:49 workflow.py:2197 DEBUG    Workflow finished in 0.016 seconds.
11:38:50 workflow.py:2154 DEBUG    Workflow version : 2.0.0
11:38:50 workflow.py:1556 DEBUG    Reading settings from `/Users/brian/Library/Application Support/Alfred 3/Workflow Data/com.sverdlik.michael/settings.json` ...
11:38:50 workflow.py:2176 ERROR    Unable to normalize state: aborted
Traceback (most recent call last):
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/workflow/workflow.py", line 2169, in run
    func(self)
  File "vagrantup.py", line 185, in main
    do_list(wf, args.list)
  File "vagrantup.py", line 117, in do_list
    add_machines(wf, _safe_get(args, 0))
  File "vagrantup.py", line 48, in add_machines
    vi = Index(fh)
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 133, in __init__
    self.machines = self.parse_v1_machines(content['machines'])
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 126, in parse_v1_machines
    return {key: Machine(key=key, **val) for key, val in mdict.iteritems()}
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 126, in <dictcomp>
    return {key: Machine(key=key, **val) for key, val in mdict.iteritems()}
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 26, in __init__
    self.normalized_state = self.normalize_state(self.state)
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 56, in normalize_state
    raise ValueError('Unable to normalize state: {0}'.format(state))
ValueError: Unable to normalize state: aborted
11:38:50 workflow.py:2179 INFO     For assistance, see: https://github.com/m1keil/alfred-vagrant-workflow
11:38:50 workflow.py:2197 DEBUG    Workflow finished in 0.016 seconds.
11:39:15 workflow.py:2154 DEBUG    Workflow version : 2.0.0
11:39:15 workflow.py:1556 DEBUG    Reading settings from `/Users/brian/Library/Application Support/Alfred 3/Workflow Data/com.sverdlik.michael/settings.json` ...
11:39:15 workflow.py:2176 ERROR    Unable to normalize state: aborted
Traceback (most recent call last):
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/workflow/workflow.py", line 2169, in run
    func(self)
  File "vagrantup.py", line 185, in main
    do_list(wf, args.list)
  File "vagrantup.py", line 117, in do_list
    add_machines(wf, _safe_get(args, 0))
  File "vagrantup.py", line 48, in add_machines
    vi = Index(fh)
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 133, in __init__
    self.machines = self.parse_v1_machines(content['machines'])
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 126, in parse_v1_machines
    return {key: Machine(key=key, **val) for key, val in mdict.iteritems()}
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 126, in <dictcomp>
    return {key: Machine(key=key, **val) for key, val in mdict.iteritems()}
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 26, in __init__
    self.normalized_state = self.normalize_state(self.state)
  File "/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/vagrant.py", line 56, in normalize_state
    raise ValueError('Unable to normalize state: {0}'.format(state))
ValueError: Unable to normalize state: aborted
11:39:15 workflow.py:2179 INFO     For assistance, see: https://github.com/m1keil/alfred-vagrant-workflow
11:39:15 workflow.py:2197 DEBUG    Workflow finished in 0.016 seconds.
11:39:16 workflow.py:2154 DEBUG    Workflow version : 2.0.0
11:39:16 workflow.py:1322 DEBUG    Opening workflow log file
11:39:16 workflow.py:2197 DEBUG    Workflow finished in 0.097 seconds.
```

**Comment by m1keil** [comment]
Thanks!
I see the problem:  one of your machines is in "aborted" state, which I'm not handling correctly.
Let me push a fix for that real quick....

**Comment by m1keil** [comment]
Hey @BrianGilbert,
could you please try v2.0.1 and let me know the status? It should solve your new problem and hopefully the old problem won't come back as well..

Thanks

**Comment by BrianGilbert** [comment]
@m1keil 
Confirmed working now.. Cheers

**Comment by m1keil** [comment]
thx for letting me know.

**Comment by BrianGilbert** [comment]
@m1keil I may have reported back to quickly..

Upping a VM seems to fail (Halting the same one works fine)...

```
15:18:02 background.py:236 DEBUG    Task `exec542009565275475638` running
15:18:02 background.py:237 DEBUG    cmd : ['python', '/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/execute.py', '--action', u'up', '--name', u'beetbox']
15:18:02 background.py:197 DEBUG    Executing task `exec542009565275475638` in background...
15:18:02 workflow.py:2353 DEBUG    Set last run version : 2.0.1
15:18:02 workflow.py:2197 DEBUG    Workflow finished in 0.092 seconds.
15:18:02 execute.py:28 DEBUG    Calling: ['vagrant', 'up', 'beetbox']
15:18:03 execute.py:43 DEBUG    Bringing machine 'beetbox' up with 'virtualbox' provider...
15:18:04 execute.py:43 DEBUG    ==> beetbox: Checking if box 'beet/box' is up to date...
15:18:06 execute.py:43 DEBUG    ==> beetbox: A newer version of the box 'beet/box' is available! You currently
15:18:06 execute.py:43 DEBUG    ==> beetbox: have version '0.2.4'. The latest is version '0.2.5'. Run
15:18:06 execute.py:43 DEBUG    ==> beetbox: `vagrant box update` to update.
15:18:07 execute.py:43 DEBUG    ==> beetbox: Setting the name of the VM: forms-vcglr.local.1464844683
15:18:07 execute.py:43 DEBUG    ==> beetbox: Clearing any previously set forwarded ports...
15:18:09 execute.py:43 DEBUG    It appears your machine doesn't support NFS, or there is not an
15:18:09 execute.py:43 DEBUG    adapter to enable NFS on this machine for Vagrant. Please verify
15:18:09 execute.py:43 DEBUG    that `nfsd` is installed on your machine, and try again. If you're
15:18:09 execute.py:43 DEBUG    on Windows, NFS isn't supported. If the problem persists, please
15:18:09 execute.py:43 DEBUG    contact Vagrant support.
15:18:09 execute.py:90 DEBUG    Return code: 1
15:18:09 background.py:243 ERROR    Command failed with [1] : ['python', '/Users/brian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.27796CCC-C4E3-4CB2-8AEC-1443EEDCAC3E/execute.py', '--action', u'up', '--name', u'beetbox']
15:18:09 background.py:248 DEBUG    Task `exec542009565275475638` finished
15:18:09 workflow.py:1556 DEBUG    Reading settings from `/Users/brian/Library/Application Support/Alfred 3/Workflow Data/com.sverdlik.michael/settings.json` ...
15:18:09 workflow.py:2353 DEBUG    Set last run version : 2.0.1
15:18:09 workflow.py:2197 DEBUG    Workflow finished in 7.003 seconds.
15:18:32 workflow.py:2154 DEBUG    Workflow version : 2.0.1
15:18:32 workflow.py:1556 DEBUG    Reading settings from `/Users/brian/Library/Application Support/Alfred 3/Workflow Data/com.sverdlik.michael/settings.json` ...
15:18:32 workflow.py:2353 DEBUG    Set last run version : 2.0.1
15:18:32 workflow.py:2197 DEBUG    Workflow finished in 0.017 seconds.
15:18:48 workflow.py:2154 DEBUG    Workflow version : 2.0.1
15:18:48 workflow.py:1556 DEBUG    Reading settings from `/Users/brian/Library/Application Support/Alfred 3/Workflow Data/com.sverdlik.michael/settings.json` ...
15:18:48 workflow.py:2353 DEBUG    Set last run version : 2.0.1
15:18:48 workflow.py:2197 DEBUG    Workflow finished in 0.017 seconds.
15:18:48 workflow.py:2154 DEBUG    Workflow version : 2.0.1
15:18:49 workflow.py:1322 DEBUG    Opening workflow log file
15:18:49 workflow.py:2197 DEBUG    Workflow finished in 0.096 seconds.
```


Also Is it supposed to notify me in some way when a task completes? if not I'd suggest adding an alert on completion..

**Comment by m1keil** [comment]
Hey again :-)

Can you please open the settings `vagrant workflow:settings` and add `:/sbin` under PATH.VAR ?
So instead of "VAR": "/usr/bin:/usr/local/bin" it should be "VAR": "/usr/bin:/usr/local/bin:/sbin"
And report back? 

The reason this is needed is because OS X doesn't pass environment variables from your shell to your apps, and I didn't think about NFS mounting and vagrant :-)

Regarding notification, yes it should, seems like another small bug.... checking

**Comment by m1keil** [comment]
Just submitted v2.0.2 which should have notifications working again.. sorry about that. Also the nfs thing should (probably) work as well.

**Comment by BrianGilbert** [comment]
Working as expected now. thanks @m1keil

**Comment by m1keil** [comment]
great!

**Comment by renestalder** [comment]
@m1keil Still have this error after I installed the workflow from Packal today. Is it possible Packal doesn't serve the current version?

**Comment by m1keil** [comment]
Hey,
yeah might be. I had troubles updating packal.
Could you try grabbing the last version from GitHub?
I'll check what's up with packal later tonight.

**Comment by renestalder** [comment]
The github version works fine.

**Comment by m1keil** [comment]
Updated Packal. Sorry it took me a while :\

**Comment by renestalder** [comment]
Thank you :)
